### host
[target.@RUSTC_HOST_ARCH@]
linker = "@HOST_CC@"

### targets
### aarch64
[target.aarch64-openwrt-linux-gnu]
linker = "aarch64-openwrt-linux-gnu-gcc"

### arm (armv7)
[target.armv7-openwrt-linux-gnueabi]
linker = "arm-openwrt-linux-gnueabi-gcc"

### mips
[target.mips-openwrt-linux-gnu]
linker = "mips-openwrt-linux-gnu-gcc"

### mipsel
[target.mipsel-openwrt-linux-gnu]
linker = "mipsel-openwrt-linux-gnu-gcc"

### x86-64
[target.x86_64-openwrt-linux-gnu]
linker = "x86_64-openwrt-linux-gnu-gcc"

### Custom profiles:
### strip
[profile.strip]
inherits = "release"
opt-level = "z"
debug = false
split-debuginfo = "off"
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
strip = true

### s(uper)strip
[profile.sstrip]
inherits = "release"
opt-level = "z"
debug = false
split-debuginfo = "off"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
strip = "symbols"

### Overrides build-script settings:
### Only for build scripts, proc macros, and their dependencies
[profile.release.build-override]
opt-level = "z"
debug = false
split-debuginfo = "off"
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
strip = true

### For any non-workspace member
[profile.release.package."*"]
opt-level = "z"
debug = false
split-debuginfo = "off"
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
strip = true

